### ISSUE TITLE
关于猫眼电影的爬虫问题

### ISSUE THREAD

**Issue by rayfay** [keejo125/web_scraping_and_data_analysis#1]
最近也在爬猫眼，通过修改时间戳 ts的方法我在实际修改中发现也还是存在问题，猫眼直接不返回数据了

**Comment by keejo125** [comment]
ts的初始值是0，后续再抓取过程中会自动变的。

**Comment by keejo125** [comment]
看来是猫眼修改了接口，现在的确没办法修改ts来获取更多数据了。

**Comment by keejo125** [comment]
测试了一下，初始ts=0时，可以获取评论数据，并返回当前的时间戳，当修改这个ts时间戳，比当前时间戳早超过1个小时的时候，就会返回空数据。现在ts被用来判断是否爬取评论了，通过ts来获取所有的评论这条路应该是彻底不通了。

**Comment by qiaoyuhub** [comment]
现在还有人试过吗，还是不太行，有没有解决办法
