### ISSUE TITLE
评论好像爬不下来了,单独打印了下data没有评论了

### ISSUE THREAD

**Issue by dfaofeng** [keejo125/web_scraping_and_data_analysis#2]
坐等作者修复

**Comment by keejo125** [comment]
是哪个网站的评论？？？

**Comment by dfaofeng** [comment]
猫眼的评论抓取不了

**Comment by keejo125** [comment]
的确是猫眼修改了接口，limit的值最大只能是15了，超过15也直接反馈空。也无法通过修改ts值来获取更多数据。目前重新推送了一下，可以获取了，但是最多只能获取1000条评论。

**Comment by keejo125** [comment]
这个接口被封了，参考这个吧  https://github.com/keejo125/web_scraping_and_data_analysis/issues/1
